core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ADMIN/ROOT APPLICATION
    path('admin/', admin.site.urls),

    # EXARTH APPLICATION
    path('exarth/', include('src.dev.urls', namespace='exarth')),

    # WFL - PROJECT ------------------------------------------
    path('', include('src.website.urls', namespace='website'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/dev/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    home, add_discussion, update_discussion, satisfied_discussion, logout_view, login_view,
    discussions, delete_discussion, discussion, add_answer, update_answer, delete_answer
)

app_name = 'exarth'
urlpatterns = [
    path('status/', home, name='status'),
    path('', TemplateView.as_view(template_name='start.html')),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),

    path('discussions/', discussions, name='discussions'),
    path('discussion/<int:discussion_id>/', discussion, name='discussion'),

    path('add/discussion/', add_discussion, name='add_discussion'),
    path('update/discussion/<int:discussion_id>/', update_discussion, name='update_discussion'),
    path('delete/discussion/<int:discussion_id>/', delete_discussion, name='delete_discussion'),

    path('add/answer/to/discussion/<int:discussion_id>/', add_answer, name='add_answer_to_discussion'),
    path('update/answer/<int:answer_id>/of/discussion/<int:discussion_id>/', update_answer,
         name='update_answer_of_discussion'),
    path('delete/answer/<int:answer_id>/of/discussion/<int:discussion_id>/', delete_answer,
         name='delete_answer_of_discussion'),
    path('satisfied/discussion/<int:discussion_id>/', satisfied_discussion, name='satisfied_discussion'),
]

src/dev/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from datetime import datetime, timedelta


class DevelopmentProject(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, default='Unknown')
    tag_line = models.CharField(max_length=255, null=False, blank=False, default='_tag_line_not_defined_until_now_')
    version = models.CharField(max_length=100, null=False, blank=False, default='v0.0.1 - alpha')
    start_date = models.DateTimeField(default=datetime.now())
    last_date = models.DateTimeField(default=datetime.now()+timedelta(weeks=+4))
    description = models.TextField(null=True, blank=True)
    logo = models.ImageField(upload_to='dev/images/project/', null=True, blank=True)

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

    def __str__(self):
        return self.name


class DevelopmentFeedback(models.Model):
    STATUS = (
        ('1', 'Pending'),
        ('2', 'Reviewed'),
        ('3', 'Completed'),
    )

    name = models.CharField(max_length=100, help_text='')
    description = RichTextField(null=True, blank=True)
    link = models.URLField(null=True, blank=True)

    status = models.CharField(max_length=1, default='1', null=False, blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Client Feedback'
        verbose_name_plural = 'Client Feedback'

    def __str__(self):
        return self.name


class DevelopmentIteration(models.Model):
    sequence = models.PositiveIntegerField(unique=True)
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='dev/images/iterations/', null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    is_current = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Development Iteration'
        verbose_name_plural = 'Development Iterations'

    def __str__(self):
        return self.name


class DevelopmentDiscussion(models.Model):

    QUESTION_TYPE = (
        ('1', 'Application Idea and Research'),
        ('2', 'Application Design UI/UX'),
        ('3', 'Business Logic'),
        ('4', 'Bugs Issues Errors and Other problems'),
        ('5', 'Missing requirements and fixes'),
        ('6', 'Security Vulnerabilities'),
        ('0', 'Undefined'),
    )

    topic = models.CharField(
        max_length=1, choices=QUESTION_TYPE,
        help_text="Select Your discussion category if you didn't find select undefined"
    )
    description = models.TextField(
        help_text='Have something in mind? lets start to write'
    )
    started_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='QUESTION_BY')

    is_answered = models.BooleanField(default=False)
    is_satisfied = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Discussion'
        verbose_name_plural = 'Discussion Board'

    def __str__(self):
        return self.question


class DevelopmentDiscussionAnswer(models.Model):

    discussion = models.ForeignKey(DevelopmentDiscussion, on_delete=models.CASCADE, null=True,
                                   blank=True)
    answer = RichTextField(null=False, blank=False)
    answer_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='ANSWERED_BY')

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Discussion Answer'
        verbose_name_plural = 'Discussion Answers'

    def __str__(self):
        return self.discussion.question

src/dev/forms.py
from django.forms import ModelForm, Textarea
from .models import DevelopmentDiscussion, DevelopmentDiscussionAnswer


class DevelopmentDiscussionForm(ModelForm):
    class Meta:
        model = DevelopmentDiscussion
        fields = (
            'topic', 'description'
        )
        widgets = {
            'question': Textarea(attrs={'cols': 80, 'rows': 10})
        }


class DevelopmentDiscussionAnswerForm(ModelForm):
    class Meta:
        model = DevelopmentDiscussionAnswer
        fields = (
            'answer',
        )
        widgets = {
            'answer': Textarea(attrs={'cols': 80, 'rows': 10})
        }

src/dev/views.py
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from .forms import DevelopmentDiscussionForm, DevelopmentDiscussionAnswerForm
from .models import (
    DevelopmentDiscussion, DevelopmentDiscussionAnswer, DevelopmentIteration, DevelopmentProject
)


def home(request):

    # CHECK AUTH
    if not request.user.is_authenticated:
        return redirect('exarth:login')

    # CHECK PROJECT
    project = DevelopmentProject.objects.first()
    if not project:
        project = DevelopmentProject.objects.create()

    iterations = DevelopmentIteration.objects.all()
    context = {
        'iterations': iterations,
        'project': project
    }
    return render(request=request, template_name='home.html', context=context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('exarth:login')


def login_view(request):
    if request.user.is_authenticated:
        return redirect('exarth:status')

    if request.method == 'POST':

        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('exarth:status')
    else:
        form = AuthenticationForm
    return render(request=request, template_name='login.html', context={'form': form})


""" ------------------------------------------------------------------------------------"""


@login_required
def discussions(request):
    context = {
        'discussions_me': DevelopmentDiscussion.objects.filter(started_by=request.user).values('pk', 'description'),
        'discussions_all': DevelopmentDiscussion.objects.exclude(started_by=request.user).values('pk', 'description'),
        'discussions': DevelopmentDiscussion.objects.all()
    }
    return render(request=request, template_name='discussions.html', context=context)


@login_required
def discussion(request, discussion_id):
    try:
        dis = DevelopmentDiscussion.objects.get(pk=discussion_id)
        discussion_answers = DevelopmentDiscussionAnswer.objects.filter(discussion=dis)
        context = {
            'discussion': dis,
            'discussion_answers': discussion_answers,
            'total_answers': discussion_answers.count()
        }
        return render(request=request, template_name='discussion.html', context=context)
    except DevelopmentDiscussion.DoesNotExist:
        messages.error(request, f"Requested discussion {discussion_id} Doesn't Exists")
        redirect('exarth:discussions')


@login_required
def add_discussion(request):
    method = request.method
    if method == 'POST':
        form = DevelopmentDiscussionForm(request.POST)
        if form.is_valid():
            success = form.save(commit=True)
            success.started_by = request.user
            success.save()

            messages.success(
                request=request,
                message=f"Hi Mr {request.user.username}! Your Question submitted Successfully"
            )

            return redirect('exarth:discussion', success.pk)
    else:
        form = DevelopmentDiscussionForm()
    context = {
        'form': form
    }

    return render(request=request, template_name='add_discussion.html', context=context)


@login_required
def update_discussion(request, discussion_id):

    try:
        question = DevelopmentDiscussion.objects.get(pk=discussion_id)

        if question.started_by != request.user:
            messages.error(request, f"You are not allowed to update this discussion")
            return redirect('exarth:discussions')
    except DevelopmentDiscussion.DoesNotExist:
        messages.error(request, f"Requested Question {discussion_id} Doesn't Exists")
        return redirect('exarth:discussions')

    method = request.method
    if method == 'POST':
        form = DevelopmentDiscussionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            messages.success(request, f"Requested Question {discussion_id} updated Successfully")
            return redirect('exarth:discussion', discussion_id)
    else:
        form = DevelopmentDiscussionForm(instance=question)

    context = {
        'form': form,
        'id': discussion_id
    }

    return render(request=request, template_name='update_discussion.html', context=context)


@login_required
def delete_discussion(request, discussion_id):
    question = None
    try:
        question = DevelopmentDiscussion.objects.get(pk=discussion_id)

        if question.started_by != request.user:
            messages.error(request, f"You are now allowed to end this discussion")
        else:
            question.delete()
            messages.success(request, f"Your discussion deleted successfully")

    except DevelopmentDiscussion.DoesNotExist:
        messages.error(request, f"Requested Question {discussion_id} Doesn't Exists")

    return redirect('exarth:discussions')


@login_required
def add_answer(request, discussion_id):
    dis = None
    try:
        dis = DevelopmentDiscussion.objects.get(pk=discussion_id)
    except DevelopmentDiscussion.DoesNotExist:
        messages.error(request, "Requested discussion doesn't exists")

    method = request.method
    if method == 'POST':
        form = DevelopmentDiscussionAnswerForm(request.POST)
        if form.is_valid():
            success = form.save(commit=True)
            success.answer_by = request.user
            success.discussion = dis

            dis.is_answered = True
            dis.save()

            success.save()

            messages.success(
                request=request,
                message=f"Your Answer to this discussion submitted Successfully"
            )
            return redirect('exarth:discussion', discussion_id)
    else:
        form = DevelopmentDiscussionAnswerForm()
    context = {
        'post': False,
        'form': form
    }

    return render(request=request, template_name='update_discussion_answer.html', context=context)


@login_required
def update_answer(request, answer_id, discussion_id):

    try:
        answer = DevelopmentDiscussionAnswer.objects.get(pk=answer_id)
        question = DevelopmentDiscussionAnswer.objects.get(pk=answer_id)

        if answer.answer_by != request.user:
            messages.error(request, f"You are not allowed to update this answer")
            return redirect('exarth:discussions')

    except DevelopmentDiscussionAnswer.DoesNotExist:
        messages.error(request, f"Requested answer doesn't exists")
        return redirect('exarth:discussions')
    except DevelopmentDiscussion.DoesNotExist:
        messages.error(request, f"Requested discussion doesn't exists")
        return redirect('exarth:discussions')

    method = request.method

    if method == 'POST':
        form = DevelopmentDiscussionAnswerForm(request.POST, instance=answer)
        if form.is_valid():
            form.save()
            messages.success(request, f"Your answer to this discussion updated Successfully")
            return redirect('exarth:discussion', discussion_id)
    else:
        form = DevelopmentDiscussionAnswerForm(instance=answer)

    context = {
        'post': True,
        'form': form,
        'answer_id': answer_id,
        'discussion_id': discussion_id
    }

    return render(request=request, template_name='update_discussion_answer.html', context=context)


@login_required
def delete_answer(request, answer_id, discussion_id):
    try:
        answer = DevelopmentDiscussionAnswer.objects.get(pk=answer_id)
        question = DevelopmentDiscussion.objects.get(pk=discussion_id)

        if answer.answer_by != request.user:
            messages.error(request, f"You are now allowed to delete this discussion")
        else:
            answer.delete()
            messages.success(request, f"Your answer to this discussion "
                                      f"deleted successfully")

    except DevelopmentDiscussionAnswer.DoesNotExist:
        messages.error(request, f"Requested answer doesn't exists")
    except DevelopmentDiscussion.DoesNotExist:
        messages.error(request, f"Requested discussion doesn't exists")

    return redirect('exarth:discussion', discussion_id)


@login_required
def satisfied_discussion(request, discussion_id):
    try:
        question = DevelopmentDiscussion.objects.get(pk=discussion_id)
        answers = DevelopmentDiscussionAnswer.objects.filter(discussion=question)

        if question.started_by != request.user:
            messages.error(request, f"TFailed to satisfy this is not your discussion")
        else:
            if len(answers) < 1:
                messages.error(
                    request,
                    f"No one answered to this question how can this be satisfied - "
                    f"if you know the answer write it down or you can end this discussion"
                )
            else:
                question.is_satisfied = True
                question.save()
                messages.success(request, f"Your answer to this discussion "
                                      f"satisfied successfully")

    except DevelopmentDiscussion.DoesNotExist:
        messages.error(request, f"Requested discussion doesn't exists")
    return redirect('exarth:discussion', discussion_id)

src/dev/templates/add_discussion.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Start Discussion
{% endblock %}


{% block content %}

    <div class="row mb-4">
        <div>
            <p class="h4 m-0">Add New Discussion</p>
            <p class="small text-muted">
                You can start discussion here on system bugs,
                errors problems and suggestions etc.
            </p>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-sm-10">
            <div class="card">

                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form|crispy }}
                        <button class="btn btn-primary">
                            <i class="fa fa-clipboard-check"></i> Submit
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/dev/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link rel="shortcsetut icon" href="{% static 'core/icons/favico.ico' %}">
    <title>
    EXARTH |
        {% block title %}

        {% endblock title %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'dev/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'dev/css/icons.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'dev/css/style.css' %}" rel="stylesheet" type="text/css">
    {% block css_links %}

    {% endblock %}


</head>
<body style="background-color: #f5f5f5;">

{# FOR ALL PAGES WIRHOUT HEADER AND DIVS #}
{% block without_body %}


    {% block header %}
        {% include 'include/header.html' %}
    {% endblock %}


    <div class="container py-4">
        <div class="row">
            {% include 'include/messages.html' %}
        </div>

        {% block content %}

        {% endblock content %}
    </div>
{% endblock %}




<script src="{% static 'dev/js/jquery.min.js' %}"></script>
<script src="{% static 'dev/js/bootstrap.bundle.min.js' %}"></script>
{% block javascript_links %}

{% endblock %}

</body>
</html>

{% block javascript_code %}

{% endblock %}

src/dev/templates/discussion.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ discussion.get_question_type_display }}
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-sm-12">

            <div class="text-right mb-4">
                {% if discussion.is_satisfied %}
                    <h4 class="font-weight-bolder text-danger">
                        <span class="badge badge-danger p-2">Satisfied and Closed</span>
                    </h4>
                {% else %}
                    <h4 class="font-weight-bolder text-success">
                        <span class="badge badge-success p-2">UnSatisfied and Open</span>
                    </h4>
                {% endif %}
            </div>

            <div class="card">
                <div class="card-header bg-white border-0">
                    <p class="m-0 h4 font-weight-bolder">
                        {{ discussion.started_by.first_name }} {{ discussion.started_by.first_name }}
                        {% if discussion.started_by == request.user %}
                            <a href="{% url 'exarth:update_discussion' discussion.pk %}"><i
                                    class="text-dark fa fa-edit"></i></a>
                        {% endif %}
                    </p>
                    <small class="text-muted font-italic">
                        {% if discussion.started_by.is_superuser %}
                            <i class="fa fa-code"></i> Development Team
                        {% elif discussion.started_by.is_staff %}
                            <i class="fa fa-user"></i> Customer Circle
                        {% else %}
                            <i class="fa fa-exclamation-circle"></i> Undefined
                        {% endif %}
                    </small>
                </div>
                <div class="card-body">
                    {# QUESTION #}
                    <div class="mb-2">
                        <p class="mb-0 card-text">
                            {{ discussion.description }}
                        </p>

                    </div>
                </div>
                <div class="card-footer border-0">
                    <div class="row">
                        <div class="col-sm-6">
                            <p class="small mt-2 text-muted">Created on: {{ discussion.created_on }}</p>
                        </div>
                        <div class="col-sm-6 text-right">
                            {% if not discussion.is_satisfied %}
                                <a class="btn btn-sm btn-primary"
                                   href="{% url 'exarth:add_answer_to_discussion' discussion.pk %}"><i
                                        class="fa fa-plus"></i> Submit Answer</a>
                                {% if discussion.started_by == request.user %}
                                    <a class="btn btn-sm btn-dark"
                                       href="{% url 'exarth:satisfied_discussion' discussion.pk %}">
                                        <i class="fa fa-check"></i> Satisfied</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if discussion_answers %}
        {% for discussion_answer in discussion_answers %}

            <div class="row pb-2">
                <div class="card-body">
                    <p class="">{{ discussion_answer.answer|safe }}</p>
                    <p class="mb-0 font-weight-bolder">
                        {{ discussion_answer.answer_by.first_name }} {{ discussion_answer.answer_by.last_name }}
                        {% if discussion_answer.answer_by == request.user %}
                            <a href="{% url 'exarth:update_answer_of_discussion' discussion_answer.pk  discussion.pk %}">
                                <i class="fa fa-edit"></i>
                            </a>
                        {% endif %}
                    </p>
                    <p class="mb-0 text-muted small font-italic">{{ discussion_answer.created_on }}</p>
                </div>
            </div>

        {% endfor %}
    {% endif %}

{% endblock %}

src/dev/templates/discussions.html
{% extends 'base.html' %}

{% block title %}
    Discussion Board
{% endblock %}


{% block content %}

    <div class="row mb-4">

        <div class="col">
            <p class="h4 m-0">Discussion Board</p>
            <p class="small text-muted">
                Discussion board holds communication between customer circle and development teams, you can add errors
                problems issues and bugs etc stay active for
                better output.
            </p>
        </div>

        <div class="col">
            <div class="text-right mb-4">
                <a class="btn btn-primary" href="{% url 'exarth:add_discussion' %}">
                    <i class="fa fa-plus"></i>
                    Start Discussion
                </a>
            </div>
        </div>

    </div>


    <div class="row">

        {% if discussions %}
            <div class="col-sm-8">

                <div class="card border-0">
                    <div class="card-body">


                        {% for discussion in discussions %}
                            <div class="mb-4">
                                <p class="">
                                    <a href="{% url 'exarth:discussion' discussion.pk %}">
                                        {{ discussion.description }}
                                    </a>
                                </p>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-0 h6 font-weight-bolder">
                                            {{ discussion.started_by.first_name }} {{ discussion.started_by.first_name }}
                                        </p>
                                        <small class="text-muted font-italic">
                                            {% if discussion.started_by.is_superuser %}
                                                <i class="fa fa-code"></i> Development Team
                                            {% elif discussion.started_by.is_staff %}
                                                <i class="fa fa-user"></i> Customer Circle
                                            {% else %}
                                                <i class="fa fa-exclamation-circle"></i> Undefined
                                            {% endif %}
                                        </small>

                                    </div>
                                    <div class="col-sm-6 text-right text-secondary">
                                        <p class="m-0">
                                            {% if discussion.is_answered %}
                                                <i
                                                        class="fa fa-check-circle text-success"></i>
                                            {% else %}
                                                <i class="fa fa-times-circle text-danger"></i>
                                            {% endif %}
                                            {% if discussion.is_satisfied %}
                                                <i
                                                        class="fa fa-check-circle text-success"></i>
                                            {% else %}
                                                <i
                                                        class="fa fa-times-circle text-danger"></i>
                                            {% endif %}
                                        </p>
                                        <p class="text-muted font-italic small">
                                            ({{ discussion.get_topic_display }})
                                        </p>

                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        {% endif %}

        <div class="col-sm-4">

            {% if discussions_me %}
                <div class="card mb-4">
                    <div class="card-header border-0">
                        <p class="m-0 card-title font-weight-bolder">Your Discussions</p>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled">
                            {% for discussion in discussions_me %}
                                <li>
                                    <a href="{% url 'exarth:discussion' discussion.pk %}">{{ discussion.description|truncatechars:35 }}</a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>

                </div>
            {% endif %}

            {% if discussions_all %}
                <div class="card mb-4">
                    <div class="card-header border-0">
                        <p class="m-0 card-title font-weight-bolder">Other Discussions</p>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled">
                            {% for discussion in discussions_all %}
                                <li>
                                    <a href="{% url 'exarth:discussion' discussion.pk %}">{{ discussion.description|truncatechars:35 }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
            {% endif %}

        </div>
    </div>


{% endblock %}

src/dev/templates/update_discussion.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update Discussion
{% endblock %}


{% block content %}

    <div class="row mb-4">
        <div>
            <p class="h4 m-0">Update Discussion</p>
            <p class="small text-muted">
                You can start update discussion here
            </p>
        </div>
    </div>


    <div class="row justify-content-center">
        <div class="col-sm-10">
            <div class="card">

                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form|crispy }}
                        <button class="btn btn-primary">
                            <i class="fa fa-edit"></i> Update
                        </button>
                        <a class="btn btn-danger" href="{% url 'exarth:delete_discussion' id %}">
                            <i class="fa fa-trash"></i> End
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

src/dev/templates/update_discussion_answer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {% if post %}
        Update
    {% else %}
        Add
    {% endif %}
    Answer
{% endblock %}


{% block content %}

    <div class="row mb-4">
        <div>
            <p class="h4 m-0">
                {% if post %}
                    Update
                {% else %}
                    Add
                {% endif %}
                answer to discussion
            </p>
            <p class="small text-muted">

            </p>
        </div>
    </div>


    <div class="row justify-content-center">
        <div class="col-sm-10">
            <div class="card">

                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form|crispy }}
                        {% if post %}
                            <button class="btn btn-primary">
                                <i class="fa fa-edit"></i> Update
                            </button>
                            <a class="btn btn-danger"
                               href="{% url 'exarth:delete_answer_of_discussion' answer_id discussion_id %}">
                                <i class="fa fa-trash"></i> Remove</a>
                        {% else %}
                            <button class="btn btn-primary">
                                <i class="fa fa-plus"></i> Add Answer
                            </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}